### ISSUE TITLE
On Raspberry Pi, nvm missing

### ISSUE THREAD

**Issue by friedger** [AbsorbingChaos/bks-setup-miner#19] opened 2020-07-17 21:27 UTC
When running the script the second time, I get this:

```
SCRIPT: NVM detected.
SCRIPT: Node.js not found, installing via NVM.
bash: line 50: nvm: command not found
```

**Comment by whoabuddy** [comment] 2020-07-20 21:00
I ran into something similar on Ubuntu Desktop, there might be a better way to source the info, will review - thank you!

**Comment by whoabuddy** [comment] 2020-07-30 17:40
This should be fixed in 6246ee0 - @friedger can you confirm if the issue is still happening?

**Comment by whoabuddy** [comment] 2020-09-06 14:15
Closing this one out as it should be resolved by the linked PR. Feel free to re-open or file a new issue if there is still an error!

**Closed by whoabuddy** 2020-09-06 14:15 UTC
Labels: bug
