### ISSUE TITLE
On Raspberry Pi, bc is missing

### ISSUE THREAD

**Issue by friedger** [AbsorbingChaos/bks-setup-miner#18] opened 2020-07-17 20:15 UTC
`bash: line 93: bc: command not found`

**Comment by whoabuddy** [comment] 2020-07-20 20:59
I could add this to the prerequisites when `apt-get` runs, it is installed in Ubuntu Server by default. bc = basic calculator.

**Comment by whoabuddy** [comment] 2020-07-30 17:41
This should be fixed in ee4bdb9 - @friedger can you confirm if the issue is still happening?

**Comment by whoabuddy** [comment] 2020-09-06 14:14
Closing this one out as it should be resolved by the linked PR. Feel free to re-open or file a new issue if there is still an error!

**Closed by whoabuddy** 2020-09-06 14:14 UTC
Labels: enhancement
